from collections import namedtuple

import pygame


nn_inputs_type = namedtuple("nn_inputs", "lw lf lb uw uf ub rw rf rb dw df db")

SQUARE_WIDTH = 25
SQUARE_HEIGHT = 25
SQUARE_BORDER_SIZE = 2

NORMAL_WINDOW_SQUARES_WIDTH = 22
NORMAL_WINDOW_SQUARES_HEIGHT = 22
NORMAL_WINDOW_WIDTH = NORMAL_WINDOW_SQUARES_WIDTH * SQUARE_WIDTH
NORMAL_WINDOW_HEIGHT = NORMAL_WINDOW_SQUARES_HEIGHT * SQUARE_HEIGHT
NORMAL_WINDOW_SIZE = (NORMAL_WINDOW_WIDTH, NORMAL_WINDOW_HEIGHT + SQUARE_HEIGHT)

AI_WINDOW_SQUARES_WIDTH = 15
AI_WINDOW_SQUARES_HEIGHT = 15
AI_WINDOW_WIDTH = AI_WINDOW_SQUARES_WIDTH * SQUARE_WIDTH
AI_WINDOW_HEIGHT = AI_WINDOW_SQUARES_HEIGHT * SQUARE_HEIGHT
AI_WINDOW_SIZE = (AI_WINDOW_WIDTH, AI_WINDOW_HEIGHT + SQUARE_HEIGHT)

MM_BUTTON_TEXTS = {0: "Classic Snake", 1: "Snake AI", 2: "Quit"}

MM_BUTTON_SQUARE_WIDTH = NORMAL_WINDOW_SQUARES_WIDTH // 2 + 1
MM_BUTTON_SQUARE_HEIGHT = 2
MM_BUTTON_WIDTH = MM_BUTTON_SQUARE_WIDTH * SQUARE_WIDTH
MM_BUTTON_HEIGHT = MM_BUTTON_SQUARE_HEIGHT * SQUARE_HEIGHT
MM_FIRST_BUTTON_X = (NORMAL_WINDOW_SQUARES_WIDTH - MM_BUTTON_SQUARE_WIDTH) // 2
MM_FIRST_BUTTON_Y = (NORMAL_WINDOW_SQUARES_HEIGHT - MM_BUTTON_SQUARE_HEIGHT) // 2 - 2 * MM_BUTTON_SQUARE_HEIGHT
MM_BUTTON_BORDER_SIZE = 3
MM_SELECTED_BUTTON_BORDER_SIZE = 5

MM_BUTTON_COLOR = (255, 130, 50)
MM_BUTTON_BORDER_COLOR = (150, 30, 30)
MM_SELECTED_BUTTON_COLOR = (100, 200, 80)
MM_SELECTED_BUTTON_BORDER_COLOR = (200, 250, 200)

MM_BUTTON_FONT = "Chilanka"
MM_BUTTON_FONT_SIZE = 28
MM_BUTTON_FONT_COLOR = MM_BUTTON_BORDER_COLOR
MM_SELECTED_BUTTON_FONT_COLOR = MM_SELECTED_BUTTON_BORDER_COLOR

SCORE_FONT = "Chilanka"
SCORE_FONT_SIZE = 18
SCORE_FONT_COLOR = MM_SELECTED_BUTTON_BORDER_COLOR

HUMAN_GAME_FPS = 10
AI_GAME_FPS = 15

NORMAL_HEAD_START_X = NORMAL_WINDOW_SQUARES_WIDTH // 2 + 1
NORMAL_HEAD_START_Y = NORMAL_WINDOW_SQUARES_HEIGHT // 2 + 1

AI_HEAD_START_X = AI_WINDOW_SQUARES_WIDTH // 2 + 1
AI_HEAD_START_Y = AI_WINDOW_SQUARES_HEIGHT // 2 + 1

SNAKE_TILE_COLOR = (40, 150, 255)
SNAKE_TILE_BORDER_COLOR = (0, 0, 0)
FRUIT_TILE_COLOR = (255, 30, 30)
FRUIT_TILE_BORDER_COLOR = (255, 255, 255)

DIRECTIONS = {"Left": (-1, 0),
              "Up": (0, -1),
              "Right": (1, 0),
              "Down": (0, 1)}
AI_WALLS = {"Left": (-1, None),
         "Up": (None, -1),
         "Right": (AI_WINDOW_SQUARES_WIDTH, None),
         "Down": (None, AI_WINDOW_SQUARES_HEIGHT)}

NUMBER_OF_GENERATIONS = 7
POPULATION_SIZE = 8
PARENTS_PERCENT = .5
CROSSOVER_RATE = .9
MUTATION_RATE = .5

NN_INPUT_LAYER_SIZE = 12
NN_HIDDEN_LAYER_1_SIZE = 8
NN_HIDDEN_LAYER_2_SIZE = 8
NN_OUTPUT_LAYER_SIZE = 3
NN_LAYERS = 4


class FruitEatenException(Exception):
    pass
